plotly/dash-slicer

- dash_3d_viewer/slicer.py
- dash_3d_viewer/utils.py
The idea is to show the low-res version of a slice while we wait for the actual slice to load.
Notes:
* The figure flickered quite a bit when being updated (on Firefox). This was greatly reduced when moving to the Image trace.
* When updating the value to request the new high-res data, the client freezes (on Chrome more than on FF), so the updating of low-res slices is slowed/halted.
* If we could detect when the slider is released, we could request the full slice at that moment, resulting in a smoother experience.
* When we implement contrast limits ... these will invalidate the low-res textures too ...
> Use Image trace and add low-res slices

- dash_3d_viewer/slicer.py
- dash_3d_viewer/utils.py
- examples/slicer_with_1_plus_2_views.py
- examples/slicer_with_2_views.py
- examples/slicer_with_3_views.py
This implements showing indicators for other slicers on the same volume. The proposed implementation allows keeping the API similar to what we had: you still simply create unit slicer objects. This keeps the API simple and flexible.
It works by making use of dictionary id's and pattern matching callbacks. Every component of the slicer has an id composed of:
context-id, scene-id, axis. When the scene-id is shared between slicer objects, they also share indicators. And this all works well by default, because the scene-id is derived from `id(volume)`.
Also consider the added example, that has two slicers for the same axis, and indeed both appear in the other slicer:
This also includes some changes to make the low-res images display exactly in the same position as the original image.
> Implement indicators

- dash_3d_viewer/slicer.py
- dash_3d_viewer/utils.py
- examples/slicer_with_1_plus_2_views.py
- examples/slicer_with_2_views.py
- examples/slicer_with_3_views.py
- tests/test_utils.py
*rebased*
This:
* Adds `spacing` and `origin` arguments to specify the position and scale of a volume.
* Update things accordingly: everything lives in "scene-coordinates" now.
* Updates the `slicer_with_1_plus_2_views.py` example to include one view with downsampled data.
* Add `reverse_y` argument.
> Support for anisotropic data.

- dash_slicer/slicer.py
- dash_slicer/utils.py
- examples/bring_your_own_slider.py
- examples/slicer_customized.py
- setup.py
- tests/test_slicer.py
- tests/test_utils.py
> Tweaking the API and cleaning up

- Procfile
- dash_slicer/slicer.py
- examples/threshold_overlay.py
> Add support for mask overlay

- Procfile
- dash_slicer/slicer.py
- examples/bring_your_own_slider.py
- examples/slicer_customized.py
- examples/slicer_with_1_plus_2_views.py
- examples/slicer_with_3_views.py
- test_deploy/requirements.txt
Closes #16
In short:
* When the graph is clicked, we set the 3D position of that click in a store. This store as a dict id.
* Each slider uses a callback with a pattern matching input to listen to these position-set-signals.
* This callback selects the dimension that applies to the current slicer, and convert the position to an index, then sets the slider value.
The disadvantage is that application code can no longer use the slider value as output, but that felt kinda iffy anyway. The new approach is for users to create a store with a similar dict-id. The advantage of this is that the slicer positions can be set from multiple sources!
> Enable navigating by clicking

- dash_slicer/slicer.py
This makes the auto-reload functionality actually work :)
The assigned `scene_id`'s are still a hash from `id(volume)`, but the hash is more predictable (and shorter).
> Make scene_id assignment result in consistent names

- dash_slicer/slicer.py
- examples/bring_your_own_slider.py
- examples/slicer_customized.py
- examples/slicer_with_1_plus_2_views.py
- examples/slicer_with_1_view.py
- examples/slicer_with_2_views.py
- examples/slicer_with_3_views.py
- examples/threshold_overlay.py
- tests/performance1.py
- tests/performance2.py
Last time I totally overlooked the effect of debug mode on the performance. The benchmarks perform much better now :)
I also saw that with debug mode there seems to be quite some added overhead per callback, even if that callback just passes a value from an input to an output. 
The debug feature most responsible for the performance penalty here seems to be `dev_tools_props_check`, so you can also disable that, and still benefit from other debug features 🚀 
Running `tests/performance1.py` now gives me:
* noop: 60-90 fps
* empty: 70- fps
* heatmap: 10 fps
* heatmapgl: 13 fps
* png: 36-40 fps
* png not reversed: 10 fps
> Improve performance

- dash_slicer/slicer.py
- examples/bring_your_own_slider.py
- examples/slicer_with_1_plus_2_views.py
- examples/slicer_with_2_views.py
- examples/slicer_with_3_views.py
- examples/threshold_overlay.py
- tests/test_slicer.py
Following up on #23, this PR improves the user experience by trying to keep the effect of a fast-changing index local to the current slicer. While dragging the slider, the current slicer is updated, but the other slicers (for the same scene_id) are not notified, nor will there be a request for new data to the server. When you stop dragging, the final value is "published", so the indicators update and the server provides the full-res data. This means all CPU cycles can be used to keep the current slicer responsive.
This is implemented using an Interval object that is turned on when the slider value is changed, and turned off when the value is published. The interval can be set to just 100ms so there is no perceived waiting time. Note that the behavior is pretty similar to the proposed …
> Add a rate limiter on the slicer's index

- dash_slicer/slicer.py
- tests/test_slicer.py
[Updated]
This PR introduces a `thumbnail_size` property of the slicer, in order to be able to choose the size of the low-resolution images uploaded and available clientside.  It is an integer, or None, in which case the full resolution data is uploaded clientside (I implemented this by not attaching the server callback, which was an easy solution).
> add thumbnail_size property

- dash_slicer/slicer.py
- examples/slicer_with_1_plus_2_views.py
- examples/slicer_with_3_views.py
- examples/threshold_overlay.py
> Add support for setting indicator color

- Procfile
- examples/all_features.py
- examples/slicer_with_3_views.py
Could be nice so that after a change you can check out this example and see if it still works.
> Add example that demos about all features

- dash_slicer/slicer.py
- dash_slicer/utils.py
- tests/test_utils.py
* Due to a bug, the rate limiting did not happen for layout changes like zooming and panning.
* Also made the rate limiting timeout larger for layout changes, because scroll zoom quickly feels jerky otherwise.
* Fix the sometimes weird initialization by preventing initial calls for one callback.
* When the image is larger in one dimension than in another, the thumbnails would be small in the smaller dimension. Changed so that the given size means the *minimal* size.
* Also fixed a bug that the stored thumbnail size would sometimes be wrong.
* Renamed lowres to thumbnail, because it can also contain fullres data.
> A few fixes and performance tweaks

- README.md
- dash_slicer/slicer.py
- update_docs_in_readme.py
Plus adding a file that I forgot to add in #35
> Some more doc tweaks

- dash_slicer/slicer.py
I added some notes that I hope will make other developers become familiar with the (ideas behind) codebase.
> Add developer notes

- README.md
- dash_slicer/slicer.py
- examples/threshold_contour.py
- examples/threshold_overlay.py
I considered using pattern matching, which would make it possible for the application to define multiple stores for additional traces. However, by simply proving a store via a property, we make the simpler cases easier, and the more complex cases can still define multiple stores and then add a callback to aggregate these into the `slicer.extra_traces`.
Possible alternative names for `extra_traces` could be e.g. `user_traces`, `more_traces.
> Add support for extra traces

- README.md
- dash_slicer/slicer.py
- tests/test_slicer.py
* Ability to reset the overlay. Closes #33.
* Write tests for the function.
* Found and fixed a bug or two.
> Improvements to create_overlay_data

- examples/set_slicer_position_interactively.py
small example that shows how to link three slicers to an interactive table-like element that both displays the current slicer positions and allows user input to change them. 
verbose labeling
> Interactive slicer example

- README.md
- dash_slicer/__init__.py
- dash_slicer/slicer.py
- examples/all_features.py
- examples/bring_your_own_slider.py
- examples/contrast.py
- examples/set_slicer_position_interactively.py
- examples/set_slicer_position_simple.py
- examples/slicer_customized.py
- examples/slicer_with_1_plus_2_views.py
- examples/slicer_with_1_view.py
- examples/slicer_with_2_views.py
- examples/slicer_with_3_views.py
- examples/threshold_contour.py
- examples/threshold_overlay.py
- requirements.txt
- test_deploy/app.py
- tests/performance1.py
- tests/performance2.py
- tests/test_slicer.py
All deprecated imports replaced.
> Fixing plotly/dash-slicer#59

- .circleci/config.yml
- .github/workflows/ci.yml
- dash_slicer/__init__.py
- dash_slicer/utils.py
* Bump version.
* Fixed a small bug (we used np.bool but that's deprecated).
* Update CI to test for py38 -py312.  (dropped 3.7 out of convenience, because black on py37 behaves differently).  
* I *did not* fix the CI build for circle-ci, because my bandwith is limited and I don't feel like looking into expired credentials right now 🤷
> bump version and fix ci
